# Generated by Django 5.1.8 on 2025-05-06 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=20)),
                ('hours', models.CharField(max_length=20)),
                ('dayOff', models.CharField(max_length=20)),
                ('ptoft', models.CharField(max_length=2)),
                ('Sunday', models.CharField(max_length=20)),
                ('Monday', models.CharField(max_length=20)),
                ('Tuesday', models.CharField(max_length=20)),
                ('Wednesday', models.CharField(max_length=20)),
                ('Thursday', models.CharField(max_length=20)),
                ('Friday', models.CharField(max_length=20)),
                ('Saturday', models.CharField(max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
